# Generated by Django 4.2 on 2024-10-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(choices=[('undefined', 'Undefined'), ('cat', 'Cat'), ('dog', 'Dog')], default='undefined', max_length=9)),
                ('owners', models.ManyToManyField(related_name='pets', to='pao.owner')),
            ],
        ),
    ]
