version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ../            # Set the context to the parent directory containing both docker/ and src/
      dockerfile: docker/backend/Dockerfile  # Path to Dockerfile within the build context
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src/backend/PetAndOwners:/PetAndOwners    # Mount the Django source code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - DB_HOST=db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
